# In-Class Programming Activity, Day 9

## Katya Kelly
## Date: 23 February 2017


```{r}
poker_deck <- c(outer((10 * 2:14), 1:4, '+'))

suits <- function(cards) {
  return(cards%%10)
}

ranks <- function(cards) {
  return(cards%/%10)
}
```

```{r}
## Function to see if the hand has a pair
is_pair <- function(five_cards) {
  max_same_rank <- max(table(ranks(five_cards)))
  min_same_rank <- min(table(ranks(five_cards)))
  
  ifelse((max_same_rank - min_same_rank == 1)||
           (max_same_rank - min_same_rank == 3), TRUE, FALSE)
}
```

```{r}
## Function to see if the hand has two pairs
is_two_pair <- function(five_cards) {
  max_num_pairs <- max(table(table(ranks(five_cards))))
  
  ifelse((max_num_pairs == 2)&&(is_pair(five_cards)), TRUE, FALSE)
}
```

```{r}
## Function to see if the hand is a 3 of a kind
is_three_of_a_kind <- function(five_cards) {
  max_same_rank <- max(table(ranks(five_cards)))
  
  ifelse(max_same_rank == 3, TRUE, FALSE)
}
```

```{r}
## Function to see if the hand is a full house
is_full_house <- function(five_cards) {
  
  ifelse(is_pair(five_cards) && is_three_of_a_kind(five_cards), TRUE, FALSE)
}
```

```{r}
## Function to see if the hand is a four of a kind
is_four_of_a_kind <- function(five_cards) {
  max_same_rank <- max(table(ranks(five_cards)))
  
  ifelse(max_same_rank == 4, TRUE, FALSE)
}
```

```{r}
## Function to see if the hand is a flush
is_flush <- function(five_cards) {
  
  max_suit <- max(table(suits(five_cards)))
  min_suit <- min(table(suits(five_cards)))
  
  ifelse(max_suit == min_suit, TRUE, FALSE)
}
```

```{r}
## Function to see if the hand is a straight
is_straight <- function(five_cards) {

  min_diff <- min(diff(sort(ranks(five_cards))))
  max_diff <- max(diff(sort(ranks(five_cards))))
  
  ifelse((min_diff == 1)&&(max_diff == 1), TRUE, FALSE)
}
```

```{r}
## Function to see if the hand is a straight flush
is_straight_flush <- function(five_cards) {
  
  ifelse((is_flush(five_cards))&&(is_straight(five_cards)), TRUE, FALSE)
}
```

```{r}
## Function to see if the hand is a royal flush
is_royal_flush <- function(five_cards) {
  
  max_rank <- max(ranks(five_cards))
  min_rank <- min(ranks(five_cards))
  
  ifelse((is_flush(five_cards)) &&
           (min_rank == 10) &&
           (max_rank == 14),TRUE, FALSE)
}
```


```{r}
## Function that calculates the best hand that can be assembled from the 5 drawn cards
before_draw <- function() {
  five_cards <- sample(poker_deck, 5)
  if (is_royal_flush(five_cards)) {
    return("Royal flush")
  } else if (is_straight_flush(five_cards)) {
    return("Straight flush")
  } else if (is_four_of_a_kind(five_cards)) {
    return("Four of a kind")
  } else if (is_full_house(five_cards)) {
    return("Full house")
  } else if (is_flush(five_cards)) {
    return("Flush")
  } else if (is_straight(five_cards)) {
    return("Straight")
  } else if (is_three_of_a_kind(five_cards)) {
    return("Three of a kind")
  } else if (is_two_pair(five_cards)) {
    return("Two pair")
  } else if (is_pair(five_cards)) {
    return("Pair")
  } else {
    return("Nothing")
  }
}

table(replicate(10000, before_draw()))
```

The results I get are very close to the ones claimed on the Wikipedia page.

## Test statements

```{r}
scoreActivity::score253(9)
```