# In-Class Programming Activity, Day 10

## Katya Kelly
## Date: 28 February 2017

```{r}
library(ISLR)

logistic <- function(x) {
  return(exp(x)/(1+exp(x)))
}
```

```{r}
linear_combine <- function(data, coefs) {
  
  result <- 0
  for (nm in names(coefs)) {
    if (nm == "intercept") {
      result <- result + coefs[[nm]]
    } else if (!nm %in% names(data)) {
      stop("Name not in data.")
    } else {
      result <- result + coefs[[nm]] * data[[nm]]
    }
  }
  return(result)
}
```

```{r}
LL_logistic <- function(data, coefs, outcome) {
  ans1 <- linear_combine(data, coefs)
  probs <- logistic(ans1)
  
  likes <- ifelse(outcome == 1, probs, 1 - probs)
  
  return(sum(log(likes)))
}
```

```{r}
best_coefs <- optim(c(intercept = 1, income = 0), fn= LL_logistic, control=list(fnscale = -1),
                    data = Default, outcome = Default$default == "Yes")
best_coefs
```

```{r}
glm(default == "Yes" ~ income, data=Default, family="binomial")
```

My results for the values of intercept and income are very close to the ones in the glm output.


## Test statements

```{r}
scoreActivity::score253(10)
```