# In-Class Programming Activity, Day 12

## Katya Kelly
## 7 March 2017

## Generating simulated data
```{r}
n_cases <- 100
red_mean <- c(1, 0)
green_mean <- c(0, -1)
blue_mean <- c(-1, 1)

covar_red <- cbind(c(3, -1.7), c(-1.7, 1))
covar_blue <- cbind(c(2, 1.5), c(1.5, 3))

One <- cbind(c(rnorm(n_cases)), c(rnorm(n_cases)))
Two <- cbind(c(rnorm(n_cases)), c(rnorm(n_cases)))
Three <- cbind(c(rnorm(n_cases)), c(rnorm(n_cases)))

Red <- One %*% chol(covar_red)
Green <- Two %*% chol(covar_red)
Blue <- Three %*% chol(covar_blue)

Red <- Red + matrix(red_mean, ncol = ncol(Red), nrow = nrow(Red), byrow = TRUE)
Green <- Green + matrix(green_mean, ncol = ncol(Green), nrow = nrow(Green), byrow = TRUE)
Blue <- Blue + matrix(blue_mean, ncol = ncol(Blue), nrow = nrow(Blue), byrow = TRUE)

Red <- data.frame(x = Red[,1], y = Red[,2], class = "red", stringsAsFactors = FALSE)
Blue <- data.frame(x = Blue[,1], y = Blue[,2], class = "blue", stringsAsFactors = FALSE)
Green <- data.frame(x = Green[,1], y = Green[,2], class = "green", stringsAsFactors = FALSE)

Same_sigma <- rbind(Red2, Green2)
Different_sigma <- rbind(Red2, Blue2)
```

## LDA and QDA
```{r}
library(MASS)
mod_LDA_one <- lda(class ~ x + y, data = Same_sigma)
mod_LDA_two <- lda(class ~ x + y, data = Different_sigma)
test_LDA_one <- predict(mod_LDA_one, newdata = Same_sigma)
test_LDA_two <- predict(mod_LDA_two, newdata = Different_sigma)

mod_QDA_one <- qda(class ~ x + y, data = Same_sigma)
mod_QDA_two <- qda(class ~ x + y, data = Different_sigma)
test_QDA_one <- predict(mod_QDA_one, newdata = Same_sigma)
test_QDA_two <- predict(mod_QDA_two, newdata = Different_sigma)
```

## Confusion matrices
```{r}
table(Same_sigma$class, test_LDA_one$class)
table(Same_sigma$class, test_QDA_one$class)
```


## Test statements

```{r}
scoreActivity::score253(12)
```