# In-Class Programming Activity, Day 13

## Katya Kelly
## 23 March 2017


```{r}
k_fold1 <- function(formula, method = lm, data = mtcars, predfun = predict, k = 10) {
 
  sets <- rep(1:k, each = nrow(data)/k, length.out = nrow(data))
  
  mspe <- numeric(k)
  for (i in 1:k) {
    For_Testing <- data[i==sets,]
    For_Training <- data[i!=sets,]
    mod <- lm(mpg ~ hp + wt + am, data = For_Training)
    pred_vals <- predict(mod, newdata = For_Testing)
    mspe[i] <- mean((For_Testing[["mpg"]] - pred_vals)^2)
  }
  error_estimate <- mean(mspe)
  
  return(error_estimate)
}

k_fold1()
```

```{r}
k_fold <- function(formula, method = lm, data = mtcars, predfun = predict, k = 10) {
 
  sets <- rep(1:k, each = nrow(data)/k, length.out = nrow(data))
  
  mspe <- numeric(k)
  for (i in 1:k) {
    For_Testing <- data[i==sets,]
    For_Training <- data[i!=sets,]
    mod <- method(formula, data = For_Training)
    pred_vals <- predfun(mod, newdata = For_Testing)
    mspe[i] <- mean((For_Testing[[as.character(formula[[2]])]] - pred_vals)^2)
  }
  error_estimate <- mean(mspe)
  
  return(error_estimate)
}

k_fold(formula = mpg ~ hp + wt + am, data=mtcars)
```


## Test statements

```{r}
scoreActivity::score253(13)
```